//communicating with hardware signals on linux systems

#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>

    // user defined signal handler for alarm
    void alarm_handler(int signo){
        
        if (signo == SIGALRM){
            printf("Alarm\n");
            alarm(2); //wait 2 seconds after each prinetd Alarm
        }

    else if (signo == SIGINT){ //CTRL C button on keyboard
        printf("CTRL+C pressed!\n");
        }
        
    else if (signo == SIGTSTP){ //CTRL Z button on keyboard
        printf("CTRL+Z pressed!\n");
        exit(1); //terminate
        }
    }

    int main(void){
        //register signal handler
        if (signal(SIGALRM, alarm_handler) == SIG_ERR){
            printf("FAIL\n");
            exit(1);
        }

        else if (signal(SIGINT, alarm_handler) == SIG_ERR){
            printf("FAIL\n");
            exit(1);
        }

        else if (signal(SIGTSTP, alarm_handler) == SIG_ERR){
            printf("FAIL\n");
            exit(1);
        }

        alarm(2);
        while(1){ //using sleep in infinite while loop to create timer
            sleep(10);
        }
    }

/*
 SIGALRM = Alarm Signal, tyically indicates expiration of timer that measures real or clock time
 SIGINT = Signal Inerrupt, Interactive attention signal, generated by application user. Example = CTRL C
 SIGSTP = Interactive Stop Signal, can be handled and ignored (unlike SIGSTOP)
 SIG_ERR = Represents a signal error
  
 */
